dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: collections.yml

driver:
  name: docker

lint: |
  set -e
  ec
  yamllint --strict --config-file .yamllint .
  ansible-lint .
  flake8

platforms:
  - name: instance
    image: debian:${MOLECULE_DEBIAN_VERSION:-bullseye}
    dockerfile: Dockerfile.j2
    override_command: false
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: /usr/bin/python3
  log: true

verifier:
  name: testinfra
