dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: bullseye
    image: debian:bullseye
    dockerfile: Dockerfile.j2
    override_command: false
    tmpfs:
      - /run
      - /tmp
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
  - name: bookworm
    image: debian:bookworm
    dockerfile: Dockerfile.j2
    override_command: false
    tmpfs:
      - /run
      - /tmp
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: /usr/bin/python3
  log: true

verifier:
  name: testinfra
  options:
    junit-xml: molecule.xml
