name: Release
'on':
  workflow_run:
    workflows:
      - Test
    branches:
      - master
    types:
      - completed
jobs:
  release:
    name: Release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: escalate/github-actions-workflows/.github/workflows/release-ansible.yml@master
    secrets:
      ANSIBLE_GALAXY_API_TOKEN: ${{ secrets.ANSIBLE_GALAXY_API_TOKEN }}
